//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USClothesWebSite.Win.Logic.LogAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://usclothes.ru/webservice/logapi", ConfigurationName="LogAPI.ILogAPI")]
    public interface ILogAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/logapi/ILogAPI/GetActionLogs", ReplyAction="http://usclothes.ru/webservice/logapi/ILogAPI/GetActionLogsResponse")]
        USClothesWebSite.DTO.ActionLog[] GetActionLogs(System.DateTime startDate, System.DateTime endDate, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/logapi/ILogAPI/GetActionLogs", ReplyAction="http://usclothes.ru/webservice/logapi/ILogAPI/GetActionLogsResponse")]
        System.Threading.Tasks.Task<USClothesWebSite.DTO.ActionLog[]> GetActionLogsAsync(System.DateTime startDate, System.DateTime endDate, string filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogAPIChannel : USClothesWebSite.Win.Logic.LogAPI.ILogAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogAPIClient : System.ServiceModel.ClientBase<USClothesWebSite.Win.Logic.LogAPI.ILogAPI>, USClothesWebSite.Win.Logic.LogAPI.ILogAPI {
        
        public LogAPIClient() {
        }
        
        public LogAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public USClothesWebSite.DTO.ActionLog[] GetActionLogs(System.DateTime startDate, System.DateTime endDate, string filter) {
            return base.Channel.GetActionLogs(startDate, endDate, filter);
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.DTO.ActionLog[]> GetActionLogsAsync(System.DateTime startDate, System.DateTime endDate, string filter) {
            return base.Channel.GetActionLogsAsync(startDate, endDate, filter);
        }
    }
}
