//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USClothesWebSite.Win.Logic.ProductAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://usclothes.ru/webservice/productapi", ConfigurationName="ProductAPI.IProductAPI")]
    public interface IProductAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProducts", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductsErrorDataFault", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        USClothesWebSite.DTO.Product[] GetProducts(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProducts", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductsResponse")]
        System.Threading.Tasks.Task<USClothesWebSite.DTO.Product[]> GetProductsAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductsByDate", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductsByDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductsByDateErrorDataF" +
            "ault", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        USClothesWebSite.DTO.Product[] GetProductsByDate(System.DateTime startDate, System.DateTime endDate, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductsByDate", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductsByDateResponse")]
        System.Threading.Tasks.Task<USClothesWebSite.DTO.Product[]> GetProductsByDateAsync(System.DateTime startDate, System.DateTime endDate, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductSizesByProduct", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductSizesByProductRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductSizesByProductErr" +
            "orDataFault", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        USClothesWebSite.DTO.ProductSize[] GetProductSizesByProduct(USClothesWebSite.DTO.Product product, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductSizesByProduct", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductSizesByProductRes" +
            "ponse")]
        System.Threading.Tasks.Task<USClothesWebSite.DTO.ProductSize[]> GetProductSizesByProductAsync(USClothesWebSite.DTO.Product product, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductSizes", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductSizesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductSizesErrorDataFau" +
            "lt", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        USClothesWebSite.DTO.ProductSize[] GetProductSizes(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductSizes", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/GetProductSizesResponse")]
        System.Threading.Tasks.Task<USClothesWebSite.DTO.ProductSize[]> GetProductSizesAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/CreateProduct", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/CreateProductResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/productapi/IProductAPI/CreateProductErrorDataFault" +
            "", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        USClothesWebSite.Win.Logic.ProductAPI.CreateProductResponse CreateProduct(USClothesWebSite.Win.Logic.ProductAPI.CreateProductRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/CreateProduct", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/CreateProductResponse")]
        System.Threading.Tasks.Task<USClothesWebSite.Win.Logic.ProductAPI.CreateProductResponse> CreateProductAsync(USClothesWebSite.Win.Logic.ProductAPI.CreateProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/UpdateProduct", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/UpdateProductResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/productapi/IProductAPI/UpdateProductErrorDataFault" +
            "", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        string UpdateProduct(USClothesWebSite.DTO.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/UpdateProduct", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/UpdateProductResponse")]
        System.Threading.Tasks.Task<string> UpdateProductAsync(USClothesWebSite.DTO.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/CreateProductSize", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/CreateProductSizeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/productapi/IProductAPI/CreateProductSizeErrorDataF" +
            "ault", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeResponse CreateProductSize(USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/CreateProductSize", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/CreateProductSizeResponse")]
        System.Threading.Tasks.Task<USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeResponse> CreateProductSizeAsync(USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/UpdateProductSize", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/UpdateProductSizeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/productapi/IProductAPI/UpdateProductSizeErrorDataF" +
            "ault", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        string UpdateProductSize(USClothesWebSite.DTO.ProductSize productSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/productapi/IProductAPI/UpdateProductSize", ReplyAction="http://usclothes.ru/webservice/productapi/IProductAPI/UpdateProductSizeResponse")]
        System.Threading.Tasks.Task<string> UpdateProductSizeAsync(USClothesWebSite.DTO.ProductSize productSize);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProduct", WrapperNamespace="http://usclothes.ru/webservice/productapi", IsWrapped=true)]
    public partial class CreateProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usclothes.ru/webservice/productapi", Order=0)]
        public USClothesWebSite.DTO.Product product;
        
        public CreateProductRequest() {
        }
        
        public CreateProductRequest(USClothesWebSite.DTO.Product product) {
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProductResponse", WrapperNamespace="http://usclothes.ru/webservice/productapi", IsWrapped=true)]
    public partial class CreateProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usclothes.ru/webservice/productapi", Order=0)]
        public string CreateProductResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usclothes.ru/webservice/productapi", Order=1)]
        public USClothesWebSite.DTO.Product product;
        
        public CreateProductResponse() {
        }
        
        public CreateProductResponse(string CreateProductResult, USClothesWebSite.DTO.Product product) {
            this.CreateProductResult = CreateProductResult;
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProductSize", WrapperNamespace="http://usclothes.ru/webservice/productapi", IsWrapped=true)]
    public partial class CreateProductSizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usclothes.ru/webservice/productapi", Order=0)]
        public USClothesWebSite.DTO.ProductSize productSize;
        
        public CreateProductSizeRequest() {
        }
        
        public CreateProductSizeRequest(USClothesWebSite.DTO.ProductSize productSize) {
            this.productSize = productSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateProductSizeResponse", WrapperNamespace="http://usclothes.ru/webservice/productapi", IsWrapped=true)]
    public partial class CreateProductSizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usclothes.ru/webservice/productapi", Order=0)]
        public string CreateProductSizeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://usclothes.ru/webservice/productapi", Order=1)]
        public USClothesWebSite.DTO.ProductSize productSize;
        
        public CreateProductSizeResponse() {
        }
        
        public CreateProductSizeResponse(string CreateProductSizeResult, USClothesWebSite.DTO.ProductSize productSize) {
            this.CreateProductSizeResult = CreateProductSizeResult;
            this.productSize = productSize;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductAPIChannel : USClothesWebSite.Win.Logic.ProductAPI.IProductAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductAPIClient : System.ServiceModel.ClientBase<USClothesWebSite.Win.Logic.ProductAPI.IProductAPI>, USClothesWebSite.Win.Logic.ProductAPI.IProductAPI {
        
        public ProductAPIClient() {
        }
        
        public ProductAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public USClothesWebSite.DTO.Product[] GetProducts(string filter) {
            return base.Channel.GetProducts(filter);
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.DTO.Product[]> GetProductsAsync(string filter) {
            return base.Channel.GetProductsAsync(filter);
        }
        
        public USClothesWebSite.DTO.Product[] GetProductsByDate(System.DateTime startDate, System.DateTime endDate, string filter) {
            return base.Channel.GetProductsByDate(startDate, endDate, filter);
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.DTO.Product[]> GetProductsByDateAsync(System.DateTime startDate, System.DateTime endDate, string filter) {
            return base.Channel.GetProductsByDateAsync(startDate, endDate, filter);
        }
        
        public USClothesWebSite.DTO.ProductSize[] GetProductSizesByProduct(USClothesWebSite.DTO.Product product, string filter) {
            return base.Channel.GetProductSizesByProduct(product, filter);
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.DTO.ProductSize[]> GetProductSizesByProductAsync(USClothesWebSite.DTO.Product product, string filter) {
            return base.Channel.GetProductSizesByProductAsync(product, filter);
        }
        
        public USClothesWebSite.DTO.ProductSize[] GetProductSizes(string filter) {
            return base.Channel.GetProductSizes(filter);
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.DTO.ProductSize[]> GetProductSizesAsync(string filter) {
            return base.Channel.GetProductSizesAsync(filter);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USClothesWebSite.Win.Logic.ProductAPI.CreateProductResponse USClothesWebSite.Win.Logic.ProductAPI.IProductAPI.CreateProduct(USClothesWebSite.Win.Logic.ProductAPI.CreateProductRequest request) {
            return base.Channel.CreateProduct(request);
        }
        
        public string CreateProduct(ref USClothesWebSite.DTO.Product product) {
            USClothesWebSite.Win.Logic.ProductAPI.CreateProductRequest inValue = new USClothesWebSite.Win.Logic.ProductAPI.CreateProductRequest();
            inValue.product = product;
            USClothesWebSite.Win.Logic.ProductAPI.CreateProductResponse retVal = ((USClothesWebSite.Win.Logic.ProductAPI.IProductAPI)(this)).CreateProduct(inValue);
            product = retVal.product;
            return retVal.CreateProductResult;
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.Win.Logic.ProductAPI.CreateProductResponse> CreateProductAsync(USClothesWebSite.Win.Logic.ProductAPI.CreateProductRequest request) {
            return base.Channel.CreateProductAsync(request);
        }
        
        public string UpdateProduct(USClothesWebSite.DTO.Product product) {
            return base.Channel.UpdateProduct(product);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProductAsync(USClothesWebSite.DTO.Product product) {
            return base.Channel.UpdateProductAsync(product);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeResponse USClothesWebSite.Win.Logic.ProductAPI.IProductAPI.CreateProductSize(USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeRequest request) {
            return base.Channel.CreateProductSize(request);
        }
        
        public string CreateProductSize(ref USClothesWebSite.DTO.ProductSize productSize) {
            USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeRequest inValue = new USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeRequest();
            inValue.productSize = productSize;
            USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeResponse retVal = ((USClothesWebSite.Win.Logic.ProductAPI.IProductAPI)(this)).CreateProductSize(inValue);
            productSize = retVal.productSize;
            return retVal.CreateProductSizeResult;
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeResponse> CreateProductSizeAsync(USClothesWebSite.Win.Logic.ProductAPI.CreateProductSizeRequest request) {
            return base.Channel.CreateProductSizeAsync(request);
        }
        
        public string UpdateProductSize(USClothesWebSite.DTO.ProductSize productSize) {
            return base.Channel.UpdateProductSize(productSize);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProductSizeAsync(USClothesWebSite.DTO.ProductSize productSize) {
            return base.Channel.UpdateProductSizeAsync(productSize);
        }
    }
}
