//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USClothesWebSite.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcel
    {
        public Parcel()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string Comments { get; set; }
        public decimal RublesPerDollar { get; set; }
        public decimal PurchaserSpentOnDelivery { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int CreateUserId { get; set; }
        public int ChangeUserId { get; set; }
    
        public virtual User ChangedBy { get; set; }
        public virtual User CreatedBy { get; set; }
        public virtual User Distributor { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
