//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USClothesWebSite.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.ProductSizes = new HashSet<ProductSize>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SubCategoryId { get; set; }
        public int BrandId { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int CreateUserId { get; set; }
        public int ChangeUserId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<ProductSize> ProductSizes { get; set; }
        public virtual User ChangedBy { get; set; }
        public virtual User CreatedBy { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
