//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USClothesWebSite.BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCartId { get; set; }
        public int Quantity { get; set; }
        public decimal TotalPrice { get; set; }
        public int SessionId { get; set; }
        public int ProductSizeId { get; set; }
    
        public virtual ProductSize ProductSize { get; set; }
        public virtual Session Session { get; set; }
    }
}
