//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USClothesWebSite.BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.ProductSize = new HashSet<ProductSize>();
        }
    
        public int SizeId { get; set; }
        public string Name { get; set; }
        public int SubCategoryId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int CreateUserId { get; set; }
        public int ChangeUserId { get; set; }
    
        public virtual ICollection<ProductSize> ProductSize { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
