//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USClothesWebSite.BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ActionLog = new HashSet<ActionLog>();
            this.Brand = new HashSet<Brand>();
            this.Brand1 = new HashSet<Brand>();
            this.Category = new HashSet<Category>();
            this.Category1 = new HashSet<Category>();
            this.Order = new HashSet<Order>();
            this.Order1 = new HashSet<Order>();
            this.OrderItem = new HashSet<OrderItem>();
            this.OrderItem1 = new HashSet<OrderItem>();
            this.Product = new HashSet<Product>();
            this.Product1 = new HashSet<Product>();
            this.ProductSize = new HashSet<ProductSize>();
            this.ProductSize1 = new HashSet<ProductSize>();
            this.Role = new HashSet<Role>();
            this.Role1 = new HashSet<Role>();
            this.Size = new HashSet<Size>();
            this.Size1 = new HashSet<Size>();
            this.SubCategory = new HashSet<SubCategory>();
            this.SubCategory1 = new HashSet<SubCategory>();
            this.User1 = new HashSet<User>();
            this.User11 = new HashSet<User>();
            this.UserRole = new HashSet<UserRole>();
            this.UserRole1 = new HashSet<UserRole>();
            this.UserRole2 = new HashSet<UserRole>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int CreateUserId { get; set; }
        public int ChangeUserId { get; set; }
    
        public virtual ICollection<ActionLog> ActionLog { get; set; }
        public virtual ICollection<Brand> Brand { get; set; }
        public virtual ICollection<Brand> Brand1 { get; set; }
        public virtual ICollection<Category> Category { get; set; }
        public virtual ICollection<Category> Category1 { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Order> Order1 { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ICollection<OrderItem> OrderItem1 { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Product> Product1 { get; set; }
        public virtual ICollection<ProductSize> ProductSize { get; set; }
        public virtual ICollection<ProductSize> ProductSize1 { get; set; }
        public virtual ICollection<Role> Role { get; set; }
        public virtual ICollection<Role> Role1 { get; set; }
        public virtual ICollection<Size> Size { get; set; }
        public virtual ICollection<Size> Size1 { get; set; }
        public virtual ICollection<SubCategory> SubCategory { get; set; }
        public virtual ICollection<SubCategory> SubCategory1 { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<User> User11 { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
        public virtual ICollection<UserRole> UserRole1 { get; set; }
        public virtual ICollection<UserRole> UserRole2 { get; set; }
    }
}
