//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USClothesWebSite.Win.Logic.AdministrationAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://usclothes.ru/webservice/administrationapi", ConfigurationName="AdministrationAPI.IAdministrationAPI")]
    public interface IAdministrationAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/administrationapi/IAdministrationAPI/GetSettings", ReplyAction="http://usclothes.ru/webservice/administrationapi/IAdministrationAPI/GetSettingsRe" +
            "sponse")]
        USClothesWebSite.DTO.Settings GetSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/administrationapi/IAdministrationAPI/GetSettings", ReplyAction="http://usclothes.ru/webservice/administrationapi/IAdministrationAPI/GetSettingsRe" +
            "sponse")]
        System.Threading.Tasks.Task<USClothesWebSite.DTO.Settings> GetSettingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/administrationapi/IAdministrationAPI/UpdateSetting" +
            "s", ReplyAction="http://usclothes.ru/webservice/administrationapi/IAdministrationAPI/UpdateSetting" +
            "sResponse")]
        string UpdateSettings(USClothesWebSite.DTO.Settings updatedSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/administrationapi/IAdministrationAPI/UpdateSetting" +
            "s", ReplyAction="http://usclothes.ru/webservice/administrationapi/IAdministrationAPI/UpdateSetting" +
            "sResponse")]
        System.Threading.Tasks.Task<string> UpdateSettingsAsync(USClothesWebSite.DTO.Settings updatedSettings);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministrationAPIChannel : USClothesWebSite.Win.Logic.AdministrationAPI.IAdministrationAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministrationAPIClient : System.ServiceModel.ClientBase<USClothesWebSite.Win.Logic.AdministrationAPI.IAdministrationAPI>, USClothesWebSite.Win.Logic.AdministrationAPI.IAdministrationAPI {
        
        public AdministrationAPIClient() {
        }
        
        public AdministrationAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministrationAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministrationAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministrationAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public USClothesWebSite.DTO.Settings GetSettings() {
            return base.Channel.GetSettings();
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.DTO.Settings> GetSettingsAsync() {
            return base.Channel.GetSettingsAsync();
        }
        
        public string UpdateSettings(USClothesWebSite.DTO.Settings updatedSettings) {
            return base.Channel.UpdateSettings(updatedSettings);
        }
        
        public System.Threading.Tasks.Task<string> UpdateSettingsAsync(USClothesWebSite.DTO.Settings updatedSettings) {
            return base.Channel.UpdateSettingsAsync(updatedSettings);
        }
    }
}
