//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USClothesWebSite.Win.Logic.ImageAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://usclothes.ru/webservice/imageapi", ConfigurationName="ImageAPI.IImageAPI")]
    public interface IImageAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/imageapi/IImageAPI/UploadPicture", ReplyAction="http://usclothes.ru/webservice/imageapi/IImageAPI/UploadPictureResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/imageapi/IImageAPI/UploadPictureErrorDataFault", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        USClothesWebSite.DTO.Picture UploadPicture(byte[] picture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/imageapi/IImageAPI/UploadPicture", ReplyAction="http://usclothes.ru/webservice/imageapi/IImageAPI/UploadPictureResponse")]
        System.Threading.Tasks.Task<USClothesWebSite.DTO.Picture> UploadPictureAsync(byte[] picture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/imageapi/IImageAPI/DeletePicture", ReplyAction="http://usclothes.ru/webservice/imageapi/IImageAPI/DeletePictureResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/imageapi/IImageAPI/DeletePictureErrorDataFault", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        void DeletePicture(USClothesWebSite.DTO.Picture picture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/imageapi/IImageAPI/DeletePicture", ReplyAction="http://usclothes.ru/webservice/imageapi/IImageAPI/DeletePictureResponse")]
        System.Threading.Tasks.Task DeletePictureAsync(USClothesWebSite.DTO.Picture picture);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageAPIChannel : USClothesWebSite.Win.Logic.ImageAPI.IImageAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageAPIClient : System.ServiceModel.ClientBase<USClothesWebSite.Win.Logic.ImageAPI.IImageAPI>, USClothesWebSite.Win.Logic.ImageAPI.IImageAPI {
        
        public ImageAPIClient() {
        }
        
        public ImageAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public USClothesWebSite.DTO.Picture UploadPicture(byte[] picture) {
            return base.Channel.UploadPicture(picture);
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.DTO.Picture> UploadPictureAsync(byte[] picture) {
            return base.Channel.UploadPictureAsync(picture);
        }
        
        public void DeletePicture(USClothesWebSite.DTO.Picture picture) {
            base.Channel.DeletePicture(picture);
        }
        
        public System.Threading.Tasks.Task DeletePictureAsync(USClothesWebSite.DTO.Picture picture) {
            return base.Channel.DeletePictureAsync(picture);
        }
    }
}
