//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USClothesWebSite.Win.Logic.ReportAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://usclothes.ru/webservice/reportapi", ConfigurationName="ReportAPI.IReportAPI")]
    public interface IReportAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/reportapi/IReportAPI/GenerateParcelsReport", ReplyAction="http://usclothes.ru/webservice/reportapi/IReportAPI/GenerateParcelsReportResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/reportapi/IReportAPI/GenerateParcelsReportErrorDat" +
            "aFault", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        USClothesWebSite.DTO.ParcelReportItem[] GenerateParcelsReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/reportapi/IReportAPI/GenerateParcelsReport", ReplyAction="http://usclothes.ru/webservice/reportapi/IReportAPI/GenerateParcelsReportResponse" +
            "")]
        System.Threading.Tasks.Task<USClothesWebSite.DTO.ParcelReportItem[]> GenerateParcelsReportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/reportapi/IReportAPI/GenerateDistributorsReport", ReplyAction="http://usclothes.ru/webservice/reportapi/IReportAPI/GenerateDistributorsReportRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USClothesWebSite.DTO.ErrorData), Action="http://usclothes.ru/webservice/reportapi/IReportAPI/GenerateDistributorsReportErr" +
            "orDataFault", Name="ErrorData", Namespace="http://usclothes.ru/dto/errordata")]
        USClothesWebSite.DTO.DistributorReportItem[] GenerateDistributorsReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://usclothes.ru/webservice/reportapi/IReportAPI/GenerateDistributorsReport", ReplyAction="http://usclothes.ru/webservice/reportapi/IReportAPI/GenerateDistributorsReportRes" +
            "ponse")]
        System.Threading.Tasks.Task<USClothesWebSite.DTO.DistributorReportItem[]> GenerateDistributorsReportAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportAPIChannel : USClothesWebSite.Win.Logic.ReportAPI.IReportAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportAPIClient : System.ServiceModel.ClientBase<USClothesWebSite.Win.Logic.ReportAPI.IReportAPI>, USClothesWebSite.Win.Logic.ReportAPI.IReportAPI {
        
        public ReportAPIClient() {
        }
        
        public ReportAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public USClothesWebSite.DTO.ParcelReportItem[] GenerateParcelsReport() {
            return base.Channel.GenerateParcelsReport();
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.DTO.ParcelReportItem[]> GenerateParcelsReportAsync() {
            return base.Channel.GenerateParcelsReportAsync();
        }
        
        public USClothesWebSite.DTO.DistributorReportItem[] GenerateDistributorsReport() {
            return base.Channel.GenerateDistributorsReport();
        }
        
        public System.Threading.Tasks.Task<USClothesWebSite.DTO.DistributorReportItem[]> GenerateDistributorsReportAsync() {
            return base.Channel.GenerateDistributorsReportAsync();
        }
    }
}
